language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    recipients:
      - fjiang91@gmail.com
      - find.keviin@gmail.com
      - terence.helsel@gmail.com
      - dc5stars@yaho.com
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "dynamic-dogs-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: dynamic-dogs
  api_key:
    secure: qymUPNtGN+7qbmQGJ+IeBVjaSiQ4q0gMHsqexHcnmFIQ8mZmnsHp5g3+9NQnq95HAjHbxLIawvVvkpVZj4WKvLQ/g9KHNssGyuNtS25kdS9l6ZF5mZTiI/7EBlHWpjaFxhSejgR/NcT8ObjaKKtlB7To+5XSM4JfPBARidEl1noktr8G273g2Fakryg4bUkF+fwQmFBzPAvebPpEVz05d0SBnG/SJmdD+Fd+v+ZWzOVRG7D3TRBIVFmqU0k6cIye/dEdMqzb8lZgDBRkEgjYHUl32k6jLXnk4SOb0dPEfN9EROrYesMHNe2A2F7cg868RhZ27zyFz4csGSjE+mNhFDNpyL/Sk+S9LZVPxxct+tEGv9sCkgk5KjsunoFScTmsehAdPvJDv4X04Cyti5mIuWwIG1r6FndAslbqVjnE+TFqGCxuR1J6fnHNR4hQaB092opW/+qMGkZNeQH/FkMnHZyN4vBI6ZIjzM4ZzknhUDJTTG7qMyL1dH3oLVAESptJVhwR9f9O73LBS9rWyyHAt+z0bdzMOGYj5YEwfS8iYmKnAjw27l3rKlUztyYG+9z6S18J7yOcal678vagtr8xHV6MiCLvf9KT8DV1KEMTo+RluoE7xnIEgpfph8UrWlfqu87rfLHvil/N+Oon5y3wiEf3oPjOy0RdCc5hq00H2t0=
